name: todo_list_app
description: To do list.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # state management
  provider: ^4.3.2+2

  # slidable
  flutter_slidable: ^0.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true